  name: CI Docker Build

# Déclencheurs du workflow
on:
  push:
    branches:
      - main

# Définition des tâches
jobs:
  # Tâche de construction de l'image Docker
  build:
    # Utiliser la dernière version d'Ubuntu
    runs-on: ubuntu-latest

    # Étapes à exécuter
    steps:
      # Récupérer le code du dépôt
      - name: Checkout code
        uses: actions/checkout@v4

      # Se connecter à Docker Hub avec les identifiants secrets
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Construire l'image Docker
      - name: Build image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-static-website:latest .

      # Pousser l'image vers Docker Hub
      - name: Push image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/devops-static-website:latest
